/**
 * Browser dev TLS certificate locations and the standalone renewal script.
 *
 * This module stays free of VS Code imports so shell tooling generators and
 * unit tests can render and validate the scripts without an extension host.
 */

export const BROWSER_TLS_DIRECTORY = "/Library/Application Support/newdlops.portmanager/browser-tls";
export const BROWSER_TLS_CA_CERT_PATH = `${BROWSER_TLS_DIRECTORY}/portmanager-root-ca.crt`;
export const BROWSER_TLS_CA_KEY_PATH = `${BROWSER_TLS_DIRECTORY}/portmanager-root-ca.key`;
export const BROWSER_TLS_SERVER_CERT_PATH = `${BROWSER_TLS_DIRECTORY}/portmanager-browser.crt`;
export const BROWSER_TLS_SERVER_KEY_PATH = `${BROWSER_TLS_DIRECTORY}/portmanager-browser.key`;
export const BROWSER_TLS_HOSTNAMES_MARKER_PATH = `${BROWSER_TLS_DIRECTORY}/hostnames.txt`;

// Certificates inside this window count as stale: manual renewal, `pm repair`,
// and the generated install script all regenerate the leaf before it expires.
export const BROWSER_TLS_RENEW_WINDOW_SECONDS = 30 * 24 * 60 * 60;
export const BROWSER_TLS_RENEW_WINDOW_MS = BROWSER_TLS_RENEW_WINDOW_SECONDS * 1000;

/** OpenSSL config for the long-lived development root CA. */
export const BROWSER_TLS_CA_OPENSSL_CONFIG_LINES: readonly string[] = [
  "[req]",
  "prompt = no",
  "distinguished_name = dn",
  "x509_extensions = v3_ca",
  "",
  "[dn]",
  "CN = Port Manager Development Root CA",
  "",
  "[v3_ca]",
  "basicConstraints = critical,CA:TRUE,pathlen:0",
  "keyUsage = critical,keyCertSign,cRLSign",
  "subjectKeyIdentifier = hash",
];

/** OpenSSL config header for the leaf; SAN entries are appended per hostname. */
export const BROWSER_TLS_SERVER_OPENSSL_CONFIG_HEADER_LINES: readonly string[] = [
  "[req]",
  "prompt = no",
  "distinguished_name = dn",
  "req_extensions = v3_req",
  "",
  "[dn]",
  "CN = Port Manager Development Browser Proxy",
  "",
  "[v3_req]",
  "basicConstraints = critical,CA:FALSE",
  "keyUsage = critical,digitalSignature,keyEncipherment",
  "extendedKeyUsage = serverAuth",
  "subjectAltName = @alt_names",
  "",
  "[alt_names]",
];

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function shellDoubleQuote(value: string): string {
  return value.replace(/(["\\$`])/g, "\\$1");
}

/**
 * Shell functions sourced into the generated hook so `pm repair` can detect a
 * stale dev TLS certificate and renew it with sudo directly in the terminal.
 *
 * Staleness here mirrors the extension's definition: leaf files missing while
 * a hostname marker exists, or the leaf entering the renewal window
 * (`openssl x509 -checkend`). Alias-set changes are extension-side repairs, so
 * this path never guesses hostnames.
 */
export function buildBrowserTlsRepairShellFunctions(renewalScriptPath: string): string {
  const escapedRenewalScriptPath = shellDoubleQuote(renewalScriptPath);

  return `__pm_browser_tls_cert_stale() {
  [ -f "${shellDoubleQuote(BROWSER_TLS_HOSTNAMES_MARKER_PATH)}" ] || return 1
  command -v openssl >/dev/null 2>&1 || return 1
  if [ ! -f "${shellDoubleQuote(BROWSER_TLS_SERVER_CERT_PATH)}" ] || [ ! -f "${shellDoubleQuote(BROWSER_TLS_SERVER_KEY_PATH)}" ]; then
    return 0
  fi
  if ! openssl x509 -checkend ${BROWSER_TLS_RENEW_WINDOW_SECONDS} -noout -in "${shellDoubleQuote(BROWSER_TLS_SERVER_CERT_PATH)}" >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

__pm_browser_tls_repair_if_stale() {
  [ "$(uname -s 2>/dev/null)" = "Darwin" ] || return 0
  __pm_browser_tls_cert_stale || return 0
  if [ ! -f "${escapedRenewalScriptPath}" ]; then
    printf '%s\\n' 'Port Manager browser TLS certificate is stale. Renew it from VS Code: "Port Manager: Renew Browser TLS Certificate".' >&2
    return 0
  fi
  printf '%s\\n' 'Port Manager browser TLS certificate is stale; renewing (requires sudo)...'
  if sudo /bin/sh "${escapedRenewalScriptPath}"; then
    printf '%s\\n' 'Port Manager browser TLS certificate renewed.'
  else
    printf '%s\\n' 'Port Manager browser TLS renewal failed. Renew it from VS Code: "Port Manager: Renew Browser TLS Certificate".' >&2
  fi
  return 0
}

`;
}

/**
 * Builds the standalone renewal script installed next to the shell hook.
 *
 * `pm repair` runs this with sudo when the dev TLS certificate is stale. The
 * script is self-contained: it reissues the leaf for the hostname set recorded
 * in the marker file, so it needs no knowledge of current logical networks and
 * works even when VS Code is closed. Alias-set changes still go through the
 * extension's install path, which regenerates the marker.
 */
export function buildBrowserTlsRenewalShellScript(): string {
  return `${[
    "#!/bin/sh",
    "# Generated by Port Manager. Renews the development browser TLS certificate",
    "# for the hostname set recorded in the marker file. Run with sudo.",
    "set -eu",
    `__pm_tls_dir=${shellQuote(BROWSER_TLS_DIRECTORY)}`,
    `__pm_tls_ca_cert=${shellQuote(BROWSER_TLS_CA_CERT_PATH)}`,
    `__pm_tls_ca_key=${shellQuote(BROWSER_TLS_CA_KEY_PATH)}`,
    `__pm_tls_server_cert=${shellQuote(BROWSER_TLS_SERVER_CERT_PATH)}`,
    `__pm_tls_server_key=${shellQuote(BROWSER_TLS_SERVER_KEY_PATH)}`,
    `__pm_tls_hosts_file=${shellQuote(BROWSER_TLS_HOSTNAMES_MARKER_PATH)}`,
    'if [ "$(id -u)" != "0" ]; then',
    "  echo 'Port Manager TLS renewal must run as root. Re-run with: sudo sh '\"$0\" >&2",
    "  exit 1",
    "fi",
    "if ! command -v openssl >/dev/null 2>&1; then",
    "  echo 'Port Manager TLS renewal requires openssl.' >&2",
    "  exit 1",
    "fi",
    'if [ ! -f "$__pm_tls_hosts_file" ]; then',
    "  echo 'No Port Manager TLS hostname marker found. Run \"Port Manager: Install Browser DNS\" in VS Code first.' >&2",
    "  exit 1",
    "fi",
    '__pm_tls_owner_user="${SUDO_USER:-}"',
    'mkdir -p "$__pm_tls_dir"',
    `if [ ! -f "$__pm_tls_ca_cert" ] || [ ! -f "$__pm_tls_ca_key" ] || ! openssl x509 -checkend ${BROWSER_TLS_RENEW_WINDOW_SECONDS} -noout -in "$__pm_tls_ca_cert" >/dev/null 2>&1; then`,
    '  rm -f "$__pm_tls_ca_cert" "$__pm_tls_ca_key"',
    '  __pm_tls_ca_conf="$__pm_tls_dir/root-ca.conf"',
    "  cat > \"$__pm_tls_ca_conf\" <<'PORTMANAGER_TLS_CA_CONF'",
    ...BROWSER_TLS_CA_OPENSSL_CONFIG_LINES,
    "PORTMANAGER_TLS_CA_CONF",
    '  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -sha256 -keyout "$__pm_tls_ca_key" -out "$__pm_tls_ca_cert" -config "$__pm_tls_ca_conf" -extensions v3_ca',
    "fi",
    '__pm_tls_server_conf="$__pm_tls_dir/server.conf"',
    '__pm_tls_server_csr="$__pm_tls_dir/server.csr"',
    "cat > \"$__pm_tls_server_conf\" <<'PORTMANAGER_TLS_SERVER_CONF'",
    ...BROWSER_TLS_SERVER_OPENSSL_CONFIG_HEADER_LINES,
    "PORTMANAGER_TLS_SERVER_CONF",
    "# The SAN list follows the marker file so renewal never drops an alias.",
    `awk 'BEGIN { n = 0 } { line = $0; gsub(/\\r/, "", line); gsub(/^[ \\t]+|[ \\t]+$/, "", line); if (line != "") { n = n + 1; printf "DNS.%d = %s\\n", n, line } }' "$__pm_tls_hosts_file" >> "$__pm_tls_server_conf"`,
    'printf \'IP.1 = 127.0.0.1\\n\' >> "$__pm_tls_server_conf"',
    'openssl req -new -newkey rsa:2048 -nodes -sha256 -keyout "$__pm_tls_server_key" -out "$__pm_tls_server_csr" -config "$__pm_tls_server_conf"',
    'openssl x509 -req -in "$__pm_tls_server_csr" -CA "$__pm_tls_ca_cert" -CAkey "$__pm_tls_ca_key" -CAcreateserial -days 825 -sha256 -out "$__pm_tls_server_cert" -extfile "$__pm_tls_server_conf" -extensions v3_req',
    'rm -f "$__pm_tls_server_csr"',
    'if [ -n "$__pm_tls_owner_user" ]; then',
    '  __pm_tls_owner_group=$(id -gn "$__pm_tls_owner_user" 2>/dev/null || printf staff)',
    '  chown "$__pm_tls_owner_user:$__pm_tls_owner_group" "$__pm_tls_ca_cert" "$__pm_tls_server_cert" "$__pm_tls_server_key" "$__pm_tls_hosts_file" 2>/dev/null || true',
    "fi",
    'chmod 600 "$__pm_tls_ca_key" "$__pm_tls_server_key" 2>/dev/null || true',
    'chmod 644 "$__pm_tls_ca_cert" "$__pm_tls_server_cert" "$__pm_tls_hosts_file" 2>/dev/null || true',
    "__pm_tls_trusted=0",
    '__pm_tls_trust_error="$__pm_tls_dir/trust-error.log"',
    'if security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$__pm_tls_ca_cert" 2>"$__pm_tls_trust_error"; then',
    "  __pm_tls_trusted=1",
    "elif grep -qi 'already exists' \"$__pm_tls_trust_error\"; then",
    "  __pm_tls_trusted=1",
    "fi",
    'if [ "$__pm_tls_trusted" != "1" ] && [ -n "$__pm_tls_owner_user" ]; then',
    '  __pm_tls_owner_home="$(dscl . -read "/Users/$__pm_tls_owner_user" NFSHomeDirectory 2>/dev/null | awk \'{print $2}\' || true)"',
    '  if [ -n "$__pm_tls_owner_home" ]; then',
    '    __pm_tls_owner_keychain="$__pm_tls_owner_home/Library/Keychains/login.keychain-db"',
    '    if [ ! -f "$__pm_tls_owner_keychain" ]; then',
    '      __pm_tls_owner_keychain="$__pm_tls_owner_home/Library/Keychains/login.keychain"',
    "    fi",
    '    if [ -f "$__pm_tls_owner_keychain" ]; then',
    '      if sudo -u "$__pm_tls_owner_user" security add-trusted-cert -d -r trustRoot -k "$__pm_tls_owner_keychain" "$__pm_tls_ca_cert" 2>"$__pm_tls_trust_error"; then',
    "        __pm_tls_trusted=1",
    "      elif grep -qi 'already exists' \"$__pm_tls_trust_error\"; then",
    "        __pm_tls_trusted=1",
    "      fi",
    "    fi",
    "  fi",
    "fi",
    'if [ "$__pm_tls_trusted" != "1" ]; then',
    "  echo 'Port Manager browser TLS CA trust registration failed. The certificate was renewed, but browsers may warn until the CA is trusted.' >&2",
    "fi",
    'rm -f "$__pm_tls_trust_error"',
    "printf 'Port Manager browser TLS certificate renewed: %s\\n' \"$(openssl x509 -enddate -noout -in \"$__pm_tls_server_cert\" 2>/dev/null || printf 'renewed')\"",
  ].join("\n")}\n`;
}
