import { existsSync } from "node:fs";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { TextDecoder } from "node:util";

const PROFILE_PRELUDE_START = "# >>> Port Manager profile prelude >>>";
const PROFILE_PRELUDE_END = "# <<< Port Manager profile prelude <<<";
const PROFILE_POSTLUDE_START = "# >>> Port Manager profile activation >>>";
const PROFILE_POSTLUDE_END = "# <<< Port Manager profile activation <<<";
const PROFILE_FINAL_NEWLINE_PREFIX = "# Port Manager original final newline: ";

interface ProfileLineRecord {
  readonly content: string;
  readonly eol: string;
}

export interface ShellProfilePlan {
  /** Shell startup file that PM owns only inside its exact marker blocks. */
  readonly filePath: string;
}

export interface ManagedShellProfileOptions {
  /** Tiny cleanup script sourced before runtime managers and prompt setup. */
  readonly preludeLine: string;
  /** Deferred activation script sourced after the user's profile body. */
  readonly postludeLine: string;
  /** Exact historical PM lines that are safe to remove during migration. */
  readonly legacyLines: readonly string[];
}

export interface ShellProfilePreludeOptions {
  /** Native hook library whose preload entry must be suspended during startup. */
  readonly hookLibraryPath: string;
  /** Runtime shim directory removed until profile initialization finishes. */
  readonly runtimeShimDirectory?: string;
  /** PM-owned BASH_ENV fragment replaced with the user's previous value. */
  readonly shellEnvRestorePath?: string;
}

/**
 * Chooses every user profile phase PM must bracket. Zsh login shells read
 * `.zprofile` before `.zshrc`; placing a prelude only in `.zshrc` is too late
 * for NVM/asdf initialized from `.zprofile`.
 */
export function getManagedShellProfilePlans(
  shellPath: string | undefined,
  homeDirectory: string,
): readonly ShellProfilePlan[] {
  const shellName = path.basename(shellPath ?? "");

  if (shellName === "zsh") {
    const plans: ShellProfilePlan[] = [
      { filePath: path.join(homeDirectory, ".zprofile") },
      { filePath: path.join(homeDirectory, ".zshrc") },
    ];
    const zloginPath = path.join(homeDirectory, ".zlogin");
    if (existsSync(zloginPath)) {
      plans.push({ filePath: zloginPath });
    }
    return plans;
  }

  if (shellName === "bash") {
    const loginProfile = [".bash_profile", ".bash_login", ".profile"]
      .map((name) => path.join(homeDirectory, name))
      .find((candidate) => existsSync(candidate)) ?? path.join(homeDirectory, ".bash_profile");
    return [
      { filePath: loginProfile },
      { filePath: path.join(homeDirectory, ".bashrc") },
    ];
  }

  if (shellName === "sh") {
    return [{ filePath: path.join(homeDirectory, ".profile") }];
  }

  return [];
}

/** Every profile PM may have managed, independent of the user's current shell. */
export function getKnownManagedShellProfilePlans(homeDirectory: string): readonly ShellProfilePlan[] {
  return [".zprofile", ".zshrc", ".zlogin", ".bash_profile", ".bash_login", ".bashrc", ".profile"].map(
    (name) => ({ filePath: path.join(homeDirectory, name) }),
  );
}

/** Builds one safely quoted POSIX source record for a managed profile block. */
export function buildShellProfileSourceLine(filePath: string): string {
  return `. ${shellSingleQuote(filePath)}`;
}

/**
 * Builds the startup-side half of the profile bracket. It uses shell builtins
 * only: no grep/tail/printf/stat subprocess may join the terminal thundering
 * herd. Static network context and hook hints stay intact for the postlude.
 */
export function buildShellProfilePreludeScript(options: ShellProfilePreludeOptions): string {
  const removePreloads = [
    shellRemovePathListEntry("DYLD_INSERT_LIBRARIES", options.hookLibraryPath),
    shellRemovePathListEntry("LD_PRELOAD", options.hookLibraryPath),
  ].join("\n");
  const removeRuntimeShim = [
    options.runtimeShimDirectory === undefined
      ? ""
      : shellRemovePathListEntry("PATH", options.runtimeShimDirectory),
    shellRemoveDynamicPathListEntry("PATH", "PORT_MANAGER_RUNTIME_SHIM_DIR"),
  ].filter((value) => value.length > 0).join("\n");
  const restoreBashEnv =
    options.shellEnvRestorePath === undefined
      ? ""
      : `case "\${BASH_ENV:-}" in
  "${shellDoubleQuote(options.shellEnvRestorePath)}"|*/portmanager-bash-env.sh|*/portmanager-bash-env-*.sh)
    if [ -n "\${PORT_MANAGER_PREV_BASH_ENV:-}" ]; then
      export BASH_ENV="\${PORT_MANAGER_PREV_BASH_ENV}"
    else
      unset BASH_ENV
    fi
    ;;
esac`;

  return `# Port Manager pre-profile suspension
# Generated by the VS Code Port Manager extension. Shell builtins only.
export PORT_MANAGER_HOOK=0
unset PORT_MANAGER_HOOK_DISABLED
export PORT_MANAGER_RUNTIME_SHIM_READY=0
${restoreBashEnv}
${removePreloads}
${removeRuntimeShim}
hash -r 2>/dev/null || true

# Library hints and network identity remain untouched for post-profile restore.
`;
}

/** Defers the existing startup hook until this sourced profile ends. */
export function buildShellProfilePostludeScript(hookScriptPath: string): string {
  return `# Port Manager post-profile activation
# Generated by the VS Code Port Manager extension.
# A login bash may source .bashrc from inside .bash_profile. Keep the outer
# profile clean and let its own postlude perform the single final activation.
if [ -n "\${BASH_VERSION:-}" ] && shopt -q login_shell 2>/dev/null; then
  case "\${BASH_SOURCE[1]##*/}" in
    .bashrc) return 0 2>/dev/null || true ;;
  esac
fi
. "${shellDoubleQuote(hookScriptPath)}"
`;
}

/**
 * Rewrites only PM-owned exact lines/blocks. The user's remaining profile body,
 * BOM, and newline style are preserved while PM moves to the true boundaries.
 */
export function rewriteManagedShellProfile(content: string, options: ManagedShellProfileOptions): string {
  const bom = content.startsWith("\uFEFF") ? "\uFEFF" : "";
  const body = bom.length > 0 ? content.slice(1) : content;
  const records = parseProfileLineRecords(body);
  const removed = removeManagedBlocks(records, options);
  const ownedLines = new Set([options.preludeLine, options.postludeLine, ...options.legacyLines]);
  const userRecords = removed.records.filter((record) => !ownedLines.has(record.content));
  const eol = records.find((record) => record.eol.length > 0)?.eol ?? "\n";
  const originalFinalNewline =
    removed.originalFinalNewline ?? (userRecords.length > 0 && userRecords[userRecords.length - 1].eol.length > 0);

  if (userRecords.length > 0 && userRecords[userRecords.length - 1].eol.length === 0) {
    userRecords[userRecords.length - 1] = { ...userRecords[userRecords.length - 1], eol };
  }

  const nextRecords: ProfileLineRecord[] = [
    { content: PROFILE_PRELUDE_START, eol },
    { content: options.preludeLine, eol },
    { content: `${PROFILE_FINAL_NEWLINE_PREFIX}${originalFinalNewline ? "present" : "absent"}`, eol },
    { content: PROFILE_PRELUDE_END, eol },
    ...userRecords,
    { content: PROFILE_POSTLUDE_START, eol },
    { content: options.postludeLine, eol },
    { content: PROFILE_POSTLUDE_END, eol },
  ];
  return `${bom}${renderProfileLineRecords(nextRecords)}`;
}

/** Installs or migrates the managed blocks without swallowing non-ENOENT errors. */
export async function upsertManagedShellProfile(
  filePath: string,
  options: ManagedShellProfileOptions,
): Promise<boolean> {
  return mutateShellProfile(filePath, (content) => rewriteManagedShellProfile(content, options), true);
}

/**
 * Upgrades an existing PM install without auto-installing into fresh profiles.
 * Exact evidence in one phase authorizes bracketing the other existing phases;
 * missing files are never created by background migration.
 */
export async function migrateExistingManagedShellProfiles(
  plans: readonly ShellProfilePlan[],
  options: ManagedShellProfileOptions,
): Promise<readonly string[]> {
  let hasExistingInstall = false;
  for (const plan of plans) {
    const content = await readShellProfile(plan.filePath);
    if (content !== undefined && hasManagedShellProfileEvidence(content, options)) {
      hasExistingInstall = true;
      break;
    }
  }
  if (!hasExistingInstall) {
    return [];
  }

  const migrated: string[] = [];
  for (const plan of plans) {
    const changed = await mutateShellProfile(
      plan.filePath,
      (content) => rewriteManagedShellProfile(content, options),
      false,
    );
    if (changed) {
      migrated.push(plan.filePath);
    }
  }
  return migrated;
}

/** Removes only PM-owned profile records and leaves every user record intact. */
export function restoreShellProfileContent(content: string, options: ManagedShellProfileOptions): string {
  const bom = content.startsWith("\uFEFF") ? "\uFEFF" : "";
  const body = bom.length > 0 ? content.slice(1) : content;
  const removed = removeManagedBlocks(parseProfileLineRecords(body), options);
  const ownedLines = new Set([options.preludeLine, options.postludeLine, ...options.legacyLines]);
  const userRecords = removed.records.filter((record) => !ownedLines.has(record.content));
  if (removed.originalFinalNewline === false && userRecords.length > 0) {
    userRecords[userRecords.length - 1] = { ...userRecords[userRecords.length - 1], eol: "" };
  }
  return `${bom}${renderProfileLineRecords(userRecords)}`;
}

/** Restores one existing profile; missing files are already in the desired state. */
export async function restoreManagedShellProfile(
  filePath: string,
  options: ManagedShellProfileOptions,
): Promise<boolean> {
  return mutateShellProfile(filePath, (content) => restoreShellProfileContent(content, options), false);
}

/** True only when a profile contains an exact PM-owned legacy or managed line. */
export function hasManagedShellProfileEvidence(content: string, options: ManagedShellProfileOptions): boolean {
  const lines = parseProfileLineRecords(content.replace(/^\uFEFF/, "")).map((record) => record.content);
  return lines.some((line) => options.legacyLines.includes(line)) || hasExactManagedBlock(
    lines,
    PROFILE_PRELUDE_START,
    options.preludeLine,
    PROFILE_PRELUDE_END,
    true,
  ) || hasExactManagedBlock(
    lines,
    PROFILE_POSTLUDE_START,
    options.postludeLine,
    PROFILE_POSTLUDE_END,
    false,
  );
}

function removeManagedBlocks(
  records: readonly ProfileLineRecord[],
  options: ManagedShellProfileOptions,
): { readonly records: ProfileLineRecord[]; readonly originalFinalNewline?: boolean } {
  const result: ProfileLineRecord[] = [];
  let originalFinalNewline: boolean | undefined;
  for (let index = 0; index < records.length; index++) {
    const line = records[index].content;
    const next = records[index + 1]?.content;
    const metadata = records[index + 2]?.content;
    const exactPreludeLength =
      line === PROFILE_PRELUDE_START && next === options.preludeLine && metadata === PROFILE_PRELUDE_END
        ? 3
        : line === PROFILE_PRELUDE_START &&
            next === options.preludeLine &&
            (metadata === `${PROFILE_FINAL_NEWLINE_PREFIX}present` || metadata === `${PROFILE_FINAL_NEWLINE_PREFIX}absent`) &&
            records[index + 3]?.content === PROFILE_PRELUDE_END
          ? 4
          : 0;
    const isExactPostlude =
      line === PROFILE_POSTLUDE_START && next === options.postludeLine && metadata === PROFILE_POSTLUDE_END;
    if (exactPreludeLength > 0) {
      if (exactPreludeLength === 4) {
        originalFinalNewline = metadata === `${PROFILE_FINAL_NEWLINE_PREFIX}present`;
      }
      index += exactPreludeLength - 1;
    } else if (isExactPostlude) {
      index += 2;
    } else {
      result.push(records[index]);
    }
  }
  return { records: result, originalFinalNewline };
}

function hasExactManagedBlock(
  lines: readonly string[],
  startMarker: string,
  sourceLine: string,
  endMarker: string,
  allowFinalNewlineMetadata: boolean,
): boolean {
  return lines.some(
    (line, index) =>
      line === startMarker &&
      lines[index + 1] === sourceLine &&
      (lines[index + 2] === endMarker ||
        (allowFinalNewlineMetadata &&
          (lines[index + 2] === `${PROFILE_FINAL_NEWLINE_PREFIX}present` ||
          lines[index + 2] === `${PROFILE_FINAL_NEWLINE_PREFIX}absent`) &&
          lines[index + 3] === endMarker)),
  );
}

function parseProfileLineRecords(content: string): ProfileLineRecord[] {
  const records: ProfileLineRecord[] = [];
  let offset = 0;
  while (offset < content.length) {
    let end = offset;
    while (end < content.length && content[end] !== "\r" && content[end] !== "\n") {
      end++;
    }
    let eol = "";
    if (end < content.length) {
      eol = content[end] === "\r" && content[end + 1] === "\n" ? "\r\n" : content[end];
    }
    records.push({ content: content.slice(offset, end), eol });
    offset = end + eol.length;
  }
  return records;
}

function renderProfileLineRecords(records: readonly ProfileLineRecord[]): string {
  return records.map((record) => `${record.content}${record.eol}`).join("");
}

/** Best-effort compare-before-write prevents stale activation windows overwriting a newer user edit. */
async function mutateShellProfile(
  filePath: string,
  transform: (content: string) => string,
  createMissing: boolean,
): Promise<boolean> {
  for (let attempt = 0; attempt < 3; attempt++) {
    const existing = await readShellProfile(filePath);
    if (existing === undefined && !createMissing) {
      return false;
    }
    const expected = existing ?? "";
    const next = transform(expected);
    if (next === expected) {
      return false;
    }

    const latest = await readShellProfile(filePath);
    if (latest !== existing) {
      continue;
    }
    await fs.writeFile(filePath, next, "utf8");
    return true;
  }

  throw new Error(`Shell profile changed while Port Manager was updating it: ${filePath}`);
}

/** Rejects invalid UTF-8 instead of replacing user bytes during a profile rewrite. */
async function readShellProfile(filePath: string): Promise<string | undefined> {
  try {
    const contents = await fs.readFile(filePath);
    new TextDecoder("utf-8", { fatal: true }).decode(contents);
    return contents.toString("utf8");
  } catch (error) {
    if (isMissingFileError(error)) {
      return undefined;
    }
    throw error;
  }
}

function shellRemovePathListEntry(name: string, entry: string): string {
  const escapedEntry = shellDoubleQuote(entry);
  const removesHookLibrary = /(?:^|[/\\])media[/\\]native[/\\]libportmanager_hook\.(?:dylib|so)$/.test(entry);
  const staleHookCase = removesHookLibrary
    ? `    */media/native/libportmanager_hook.dylib|*/media/native/libportmanager_hook.so) continue ;;`
    : "";

  return `__pm_profile_path_rest=""
__pm_profile_path_remaining="\${${name}:-}"
while [ -n "$__pm_profile_path_remaining" ]; do
  case "$__pm_profile_path_remaining" in
    *:*) __pm_profile_path_entry="\${__pm_profile_path_remaining%%:*}"; __pm_profile_path_remaining="\${__pm_profile_path_remaining#*:}" ;;
    *) __pm_profile_path_entry="$__pm_profile_path_remaining"; __pm_profile_path_remaining="" ;;
  esac
  if [ -z "$__pm_profile_path_entry" ] || [ "$__pm_profile_path_entry" = "${escapedEntry}" ]; then
    continue
  fi
${staleHookCase.length > 0 ? `  case "$__pm_profile_path_entry" in\n${staleHookCase}\n  esac` : ""}
  if [ -z "$__pm_profile_path_rest" ]; then
    __pm_profile_path_rest="$__pm_profile_path_entry"
  else
    __pm_profile_path_rest="$__pm_profile_path_rest:$__pm_profile_path_entry"
  fi
done
if [ -n "$__pm_profile_path_rest" ]; then export ${name}="$__pm_profile_path_rest"; else unset ${name}; fi
unset __pm_profile_path_entry __pm_profile_path_remaining __pm_profile_path_rest`;
}

/** Removes an env-selected entry without evaluating it through `eval`. */
function shellRemoveDynamicPathListEntry(name: string, entryVariable: string): string {
  return `if [ -n "\${${entryVariable}:-}" ]; then
  __pm_profile_path_rest=""
  __pm_profile_path_remaining="\${${name}:-}"
  while [ -n "$__pm_profile_path_remaining" ]; do
    case "$__pm_profile_path_remaining" in
      *:*) __pm_profile_path_entry="\${__pm_profile_path_remaining%%:*}"; __pm_profile_path_remaining="\${__pm_profile_path_remaining#*:}" ;;
      *) __pm_profile_path_entry="$__pm_profile_path_remaining"; __pm_profile_path_remaining="" ;;
    esac
    if [ -z "$__pm_profile_path_entry" ] || [ "$__pm_profile_path_entry" = "\${${entryVariable}}" ]; then
      continue
    fi
    if [ -z "$__pm_profile_path_rest" ]; then
      __pm_profile_path_rest="$__pm_profile_path_entry"
    else
      __pm_profile_path_rest="$__pm_profile_path_rest:$__pm_profile_path_entry"
    fi
  done
  if [ -n "$__pm_profile_path_rest" ]; then export ${name}="$__pm_profile_path_rest"; else unset ${name}; fi
  unset __pm_profile_path_entry __pm_profile_path_remaining __pm_profile_path_rest
fi`;
}

function shellDoubleQuote(value: string): string {
  return value.replace(/(["\\$`])/g, "\\$1");
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function isMissingFileError(error: unknown): boolean {
  return error instanceof Error && "code" in error && error.code === "ENOENT";
}
